# Generated by Django 3.2.2 on 2021-05-20 14:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_single', models.BooleanField(default=True)),
                ('required', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField()),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.cafe')),
            ],
            options={
                'verbose_name': 'Modifier',
                'verbose_name_plural': 'Modifiers',
                'db_table': 'modifiers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='products/%y/%m/%d')),
                ('name', models.CharField(max_length=150)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('tax_present', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'db_table': 'product_sizes',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products/category/%y/%m/%d')),
                ('available', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('position', models.PositiveIntegerField()),
                ('is_kitchen', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='companies.menu')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'product_categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='modifier',
            field=models.ManyToManyField(to='products.Modifier'),
        ),
        migrations.CreateModel(
            name='ModifierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('default', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField()),
                ('modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.modifier')),
            ],
            options={
                'verbose_name': 'Modifier Item',
                'verbose_name_plural': 'Modifier Items',
                'db_table': 'modifier_items',
            },
        ),
    ]
