# Generated by Django 3.2.2 on 2021-05-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='modifier',
            field=models.ManyToManyField(blank=True, to='products.Modifier'),
        ),
        migrations.AlterField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tax_present',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='end',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='start',
            field=models.TimeField(null=True),
        ),
    ]
