# Generated by Django 3.2.2 on 2021-05-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210522_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modifier',
            new_name='modifiers',
        ),
    ]
