# Generated by Django 3.2.2 on 2021-05-26 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_employee_user'),
        ('products', '0005_rename_modifier_product_modifiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifier',
            name='company',
        ),
        migrations.AddField(
            model_name='modifier',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='companies.menu'),
            preserve_default=False,
        ),
    ]
