# Generated by Django 3.2.2 on 2021-06-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210526_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
