# Generated by Django 3.2.2 on 2021-06-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsize_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quickest_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
