# Generated by Django 3.2.2 on 2021-06-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modifier',
            options={'ordering': ('-id',), 'verbose_name': 'Modifier', 'verbose_name_plural': 'Modifiers'},
        ),
        migrations.AlterModelOptions(
            name='modifieritem',
            options={'ordering': ('-id',), 'verbose_name': 'Modifier Item', 'verbose_name_plural': 'Modifier Items'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-id',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ('-id',), 'verbose_name': 'Product Size', 'verbose_name_plural': 'Product Sizes'},
        ),
    ]
