# Generated by Django 3.2.2 on 2021-06-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tax_present',
            new_name='tax_percent',
        ),
    ]
