# Generated by Django 3.2.2 on 2021-08-05 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_tax_present_product_tax_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsize',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
