# Generated by Django 3.2.2 on 2021-08-05 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20210805_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifier',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifier',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='modifieritem',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modifieritem',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
