# Generated by Django 3.2.2 on 2021-08-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20210805_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_exchange_free_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_give_point',
            field=models.BooleanField(default=False),
        ),
    ]
