# Generated by Django 3.2.2 on 2021-09-01 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_cafe_menu'),
        ('products', '0015_auto_20210828_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeProductState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='not_available_products', to='companies.cafe')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'cafe_products_state',
            },
        ),
    ]
