# Generated by Django 3.2.2 on 2021-10-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifier',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='modifieritem',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
