# Generated by Django 3.2.2 on 2021-05-23 15:11

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_auto_20210522_0501'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0004_alter_cafe_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('instruction', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.cafe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_carts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_unique_id', models.CharField(blank=True, editable=False, max_length=120, null=True, unique=True, verbose_name='Order Id')),
                ('sub_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('new', 'New'), ('paid', 'Paid'), ('ready', 'Ready'), ('refund', 'Refund'), ('sent_out', 'Sent out'), ('delivered', 'Delivered')], default='new', max_length=60)),
                ('pre_order', models.BooleanField(default=False)),
                ('pre_order_date', models.DateTimeField(blank=True, null=True)),
                ('tip', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_confirm', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='companies.cafe')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.delivery')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_name', models.CharField(max_length=50)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('product_modifiers', models.ManyToManyField(blank=True, to='products.ModifierItem')),
                ('product_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='FavoriteCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cart_items', to='orders.favoritecart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_modifiers', models.ManyToManyField(blank=True, to='products.ModifierItem')),
                ('product_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize')),
            ],
            options={
                'db_table': 'favorite_cart_items',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_modifiers', models.ManyToManyField(blank=True, to='products.ModifierItem')),
                ('product_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productsize')),
            ],
            options={
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.cafe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
