# Generated by Django 3.2.2 on 2021-06-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_customer_order_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_price',
            new_name='product_total_price',
        ),
    ]
