# Generated by Django 3.2.2 on 2021-06-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_product_price_orderitem_product_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_total_price',
            new_name='product_price',
        ),
    ]
