# Generated by Django 3.2.2 on 2021-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_rename_product_total_price_orderitem_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tip',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tip_percent',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
