# Generated by Django 3.2.2 on 2021-07-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pre_order_timestamp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
