# Generated by Django 3.2.2 on 2021-07-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_pre_order_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pre_order_date',
        ),
    ]
