# Generated by Django 3.2.2 on 2021-07-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_order_pre_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
