# Generated by Django 3.2.2 on 2021-07-17 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20210717_0404'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
