# Generated by Django 3.2.2 on 2021-07-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_free',
        ),
    ]
