# Generated by Django 3.2.2 on 2021-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_cartitem_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='modifiers_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
