# Generated by Django 3.2.2 on 2021-07-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20210727_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
