# Generated by Django 3.2.2 on 2021-08-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20210810_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('new', 'New'), ('ready', 'Ready'), ('refund', 'Refund'), ('sent_out', 'Sent out'), ('delivered', 'Delivered')], default='waiting', max_length=60),
        ),
    ]
