# Generated by Django 3.2.2 on 2021-08-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_remove_order_is_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_unique_id',
        ),
    ]
