# Generated by Django 3.2.2 on 2021-08-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_remove_order_order_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
