# Generated by Django 3.2.2 on 2021-09-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20210907_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='free_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
