# Generated by Django 3.2.2 on 2021-05-20 14:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='cafe/logo', verbose_name='Cafe logo')),
                ('name', models.CharField(max_length=255, verbose_name='Cafe name')),
                ('description', models.TextField(null=True, verbose_name='Description cafe')),
                ('call_center', models.CharField(max_length=50, verbose_name='Phone')),
                ('website', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Blocked'), (1, 'Active'), (2, 'Pending')], default=0)),
                ('location', django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326)),
                ('country', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=220, null=True)),
                ('state', localflavor.us.models.USStateField(max_length=2, null=True)),
                ('postal_code', models.CharField(max_length=12, null=True)),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address 1')),
                ('second_address', models.TextField(blank=True, null=True, verbose_name='Address 2')),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=100)),
                ('cafe_timezone', timezone_field.fields.TimeZoneField(default='UTC')),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_max_distance', models.IntegerField(default=0, null=True)),
                ('delivery_min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_km_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_min_time', models.IntegerField(default=30)),
                ('version', models.PositiveIntegerField(blank=True, default=1)),
                ('order_limit', models.IntegerField(blank=True, default=10, verbose_name='Order limit per window')),
                ('order_time_limit', models.IntegerField(blank=True, default=10, verbose_name='Order limit window')),
            ],
            options={
                'verbose_name': 'Cafe',
                'verbose_name_plural': 'Cafes',
                'db_table': 'cafes',
            },
        ),
        migrations.CreateModel(
            name='CafePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cafe/album')),
            ],
            options={
                'verbose_name': 'Cafe Photo',
                'verbose_name_plural': 'Cafe Photos',
                'db_table': 'cafe_photos',
            },
        ),
        migrations.CreateModel(
            name='CafeWeekTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=15)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cafe Week Time',
                'verbose_name_plural': 'Cafes Week Time',
                'db_table': 'cafes_week_time',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activate', models.BooleanField(default=False, verbose_name='Company status')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
                ('ex_point', models.PositiveSmallIntegerField(default=10, verbose_name='Exchange point')),
                ('validity_point_day', models.PositiveSmallIntegerField(default=10, verbose_name='Exchange validity point')),
                ('pub_show_reviews', models.BooleanField(default=True, verbose_name='Make reviews public')),
                ('pub_show_like', models.BooleanField(default=True, verbose_name='Make like public')),
                ('cashback_percent', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Company cashback percent')),
                ('logo', models.ImageField(upload_to='companies/logos', verbose_name='Company Logo')),
                ('loading_app_image', models.ImageField(upload_to='companies/app', verbose_name='App image')),
                ('app_image_morning', models.ImageField(upload_to='companies/app', verbose_name='Background image in the morning')),
                ('app_image_day', models.ImageField(upload_to='companies/app', verbose_name='Background image in the afternoon')),
                ('app_image_evening', models.ImageField(upload_to='companies/app', verbose_name='Background image in evening')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='companies.company')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'db_table': 'menus',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('employee_position', models.SmallIntegerField(choices=[(1, 'Manager'), (2, 'Cashier')])),
                ('cafes', models.ManyToManyField(blank=True, related_name='employees', to='companies.Cafe')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
            },
        ),
    ]
