# Generated by Django 3.2.2 on 2021-05-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_auto_20210526_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='exchangeable_point',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='expiration_days',
        ),
        migrations.AddField(
            model_name='company',
            name='exchangeable_point',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='company',
            name='expiration_days',
            field=models.IntegerField(default=30),
        ),
    ]
