# Generated by Django 3.2.2 on 2021-06-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_alter_takkfeeforcompany_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takkfeeforcompany',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
