# Generated by Django 3.2.2 on 2021-07-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_takkgeneralsettings'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='takkgeneralsettings',
            table='takk_general_settings',
        ),
    ]
