# Generated by Django 3.2.2 on 2021-07-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_alter_takkgeneralsettings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='takkgeneralsettings',
            name='charge_limit',
            field=models.IntegerField(null=True),
        ),
    ]
