# Generated by Django 3.2.2 on 2021-08-13 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_auto_20210813_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cafe',
            name='updated_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
