# Generated by Django 3.2.2 on 2021-08-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0024_remove_employee_notification_cafes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cashback_percent',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='takkgeneralsettings',
            name='cashback',
            field=models.FloatField(default=5),
        ),
    ]
