# Generated by Django 3.2.2 on 2021-08-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0025_auto_20210820_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
