# Generated by Django 3.2.2 on 2021-08-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0026_auto_20210826_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='exchangeable_products',
        ),
        migrations.RemoveField(
            model_name='cafe',
            name='give_points',
        ),
    ]
