# Generated by Django 3.2.2 on 2021-09-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_cafe_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='validity_point_day',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Exchange validity point'),
        ),
    ]
