# Generated by Django 3.2.2 on 2021-05-31 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_freeitem_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_os',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('android', 'Android'), ('ios', 'IOS')], max_length=7, null=True, verbose_name='mobile os'),
        ),
    ]
