# Generated by Django 3.2.2 on 2021-06-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_alter_cafe_menu'),
        ('users', '0004_userfavoritecafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_cafes',
            field=models.ManyToManyField(blank=True, to='companies.Cafe'),
        ),
        migrations.DeleteModel(
            name='UserFavoriteCafe',
        ),
    ]
