# Generated by Django 3.2.2 on 2021-06-21 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210611_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freeitem',
            old_name='expiration_days',
            new_name='expiration_dt',
        ),
    ]
