# Generated by Django 3.2.2 on 2021-06-29 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_budgettransaction_status'),
        ('users', '0006_rename_expiration_days_freeitem_expiration_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetfillhistory',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.budgettransaction'),
        ),
    ]
