# Generated by Django 3.2.2 on 2021-07-02 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_remove_order_pre_order_date'),
        ('users', '0007_budgetfillhistory_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbackhistory',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
