# Generated by Django 3.2.2 on 2021-07-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_cashbackhistory_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
