# Generated by Django 3.2.2 on 2021-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_usernotification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='body',
            field=models.CharField(max_length=255),
        ),
    ]
