# Generated by Django 3.2.2 on 2021-09-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_usernotification_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ('-created_dt',)},
        ),
        migrations.AlterModelTable(
            name='usernotification',
            table='user_notifications',
        ),
    ]
