# Generated by Django 3.2.2 on 2021-09-21 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210908_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='batch_payment',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stripe_card_id',
        ),
    ]
