# Generated by Django 3.2.2 on 2021-09-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210921_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetfillhistory',
            old_name='fill_date',
            new_name='created_dt',
        ),
    ]
