# Generated by Django 3.2.2 on 2021-09-21 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_fill_date_budgetfillhistory_created_dt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='freeitem',
            options={'ordering': ('-created_dt',)},
        ),
        migrations.RenameField(
            model_name='freeitem',
            old_name='created_at',
            new_name='created_dt',
        ),
    ]
