# Generated by Django 3.2.2 on 2021-10-04 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210921_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='auto_fill',
            new_name='is_auto_fill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='auto_fill_min_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_os',
        ),
        migrations.AddField(
            model_name='user',
            name='auto_fill_tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.budgettariff'),
        ),
    ]
