# Generated by Django 3.2.2 on 2021-06-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_transaction'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='stripetransaction',
            name='takk_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stripetransaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In process'), (1, 'Successful'), (2, 'Failed')], default=0),
        ),
    ]
