# Generated by Django 3.2.2 on 2021-06-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_companycard'),
        ('payment', '0002_auto_20210628_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripetransaction',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.cafe'),
        ),
    ]
