# Generated by Django 3.2.2 on 2021-06-29 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_stripetransaction_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripetransaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'In process'), (1, 'Succeeded'), (2, 'Failed')], default=0),
        ),
    ]
