# Generated by Django 3.2.2 on 2021-06-30 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_stripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='payment_method_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='stripecustomer',
            name='update_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
