# Generated by Django 3.2.2 on 2021-06-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_auto_20210630_0544'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='email',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
