# Generated by Django 3.2.2 on 2021-06-30 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0010_stripecustomer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeInvoiceTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=250)),
                ('invoice_id', models.CharField(max_length=250)),
                ('total_amount', models.IntegerField()),
                ('total_takk_fee', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('update_dt', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'Draft'), (1, 'Open'), (2, 'Paid'), (3, 'Failed')], default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_invoice_transaction',
            },
        ),
    ]
