# Generated by Django 3.2.2 on 2021-06-30 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_companycard'),
        ('orders', '0016_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0011_stripeinvoicetransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeInvoiceItemTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_item_id', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('takk_fee', models.IntegerField()),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.cafe')),
                ('invoice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.stripeinvoicetransactions')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_invoice_item',
            },
        ),
    ]
