# Generated by Django 3.2.2 on 2021-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_stripeinvoiceitemtransactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=250)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
