# Generated by Django 3.2.2 on 2021-07-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0015_budgettransaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='stripecustomer',
            name='payment_method_id',
        ),
    ]
