# Generated by Django 3.2.2 on 2021-07-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0016_auto_20210710_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(max_length=250, null=True)),
                ('brand', models.CharField(max_length=10)),
                ('last4', models.CharField(max_length=4)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'customer_cards',
            },
        ),
    ]
