# Generated by Django 3.2.2 on 2021-07-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0020_stripechargetransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercard',
            old_name='cart_id',
            new_name='card_id',
        ),
    ]
