# Generated by Django 3.2.2 on 2021-07-20 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_alter_takkgeneralsettings_charge_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0024_remove_cartitem_is_free'),
        ('payment', '0026_rename_is_capture_stripechargetransaction_is_cancel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeOnlineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=250)),
                ('amount', models.IntegerField()),
                ('takk_fee', models.IntegerField(default=0)),
                ('created_dt', models.DateTimeField(auto_now_add=True)),
                ('updated_dt', models.DateTimeField(auto_now=True)),
                ('cafe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.cafe')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stripe_online_transactions',
                'ordering': ('-created_dt',),
            },
        ),
        migrations.DeleteModel(
            name='StripeTransaction',
        ),
    ]
