# Generated by Django 3.2.2 on 2021-07-21 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0027_auto_20210720_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgettransaction',
            name='status',
        ),
    ]
