# Generated by Django 3.2.2 on 2021-07-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0029_orderpaymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripeonlinetransaction',
            name='cafe',
        ),
        migrations.RemoveField(
            model_name='stripeonlinetransaction',
            name='order',
        ),
        migrations.RemoveField(
            model_name='stripeonlinetransaction',
            name='user',
        ),
        migrations.DeleteModel(
            name='BalanceTransaction',
        ),
        migrations.DeleteModel(
            name='StripeOnlineTransaction',
        ),
    ]
