# Generated by Django 3.2.2 on 2021-07-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0030_auto_20210723_0810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpaymenttransaction',
            options={'ordering': ('-created_dt',)},
        ),
    ]
