# Generated by Django 3.2.2 on 2021-07-23 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0032_paymentordertransactionrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentordertransactionrefund',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentordertransactionrefund',
            name='is_refund',
            field=models.BooleanField(default=False),
        ),
    ]
