# Generated by Django 3.2.2 on 2021-07-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0033_auto_20210723_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentordertransactionrefund',
            name='is_refund',
        ),
        migrations.AddField(
            model_name='paymentordertransactionrefund',
            name='refund_id',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
