# Generated by Django 3.2.2 on 2021-07-24 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0035_paymentordertransactionrefund_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentordertransactionrefund',
            old_name='user',
            new_name='customer',
        ),
    ]
