# Generated by Django 3.2.2 on 2021-07-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0036_rename_user_paymentordertransactionrefund_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentordertransactionrefund',
            old_name='customer',
            new_name='user',
        ),
    ]
