# Generated by Django 3.2.2 on 2021-07-25 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_remove_cartitem_is_free'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0037_rename_customer_paymentordertransactionrefund_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='refund_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='refund_description',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='refund_id',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='refund_order_items',
            field=models.ManyToManyField(blank=True, to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='takk_fee',
            field=models.IntegerField(default=0),
        ),
    ]
