# Generated by Django 3.2.2 on 2021-07-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0039_delete_paymentordertransactionrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='last4',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
