# Generated by Django 3.2.2 on 2021-07-26 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0040_auto_20210725_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payment.customercard'),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='final_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='payment.orderpaymenttransaction'),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='is_capture',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='orderpaymenttransaction',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'Online payment'), (1, 'Balance payment'), (2, 'Save card payment')]),
        ),
    ]
