# Generated by Django 3.2.2 on 2021-08-13 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0042_auto_20210813_0540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='create_dt',
            new_name='created_dt',
        ),
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='update_dt',
            new_name='updated_dt',
        ),
    ]
