# Generated by Django 3.2.2 on 2021-08-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0043_auto_20210813_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpaymenttransaction',
            name='payment_type',
            field=models.SmallIntegerField(choices=[(0, 'Online payment'), (1, 'Balance payment'), (2, 'Save card payment'), (3, 'Terminal payment')]),
        ),
    ]
