# Generated by Django 3.2.2 on 2021-09-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0044_alter_orderpaymenttransaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecustomer',
            name='customer_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
