# Generated by Django 3.2.2 on 2021-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0046_alter_orderpaymenttransaction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderpaymenttransaction',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='orderpaymenttransaction',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='orderpaymenttransaction',
            name='refund_order_items',
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='customer_cashback',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='order_detail',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='refund_detail',
            field=models.TextField(max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderpaymenttransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderpaymenttransaction',
            name='takk_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
