# Generated by Django 3.2.2 on 2021-10-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0047_auto_20211005_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpaymenttransaction',
            name='refund_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
