# Generated by Django 3.2.2 on 2021-10-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0048_orderpaymenttransaction_refund_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercard',
            name='is_confirm_off_session',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customercard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
