# Generated by Django 3.2.2 on 2021-10-08 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0049_auto_20211008_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripecustomer',
            old_name='verified',
            new_name='is_verified',
        ),
    ]
